
"""Surface inventory of the target.

What the target exposes, what each piece is trusted to do, and where the audit
touches it.  Generated by reading the source rather than by running it, so it is
a map of claims -- vuln/ checks whether the claims hold.
"""

TARGET = "hardwarekeyemulator"
COMMIT = "0fac0f6"
LINES_SRC = 4966
LINES_WITH_TESTS = 5799

SURFACE = {
    "ctap2_core.py": {
        "role": "the authenticator",
        "lines": None,
        "claims": [
            "P-256 credential generation and COSE encoding",
            "UP/UV gating through injected callables",
            "resident (discoverable) credentials",
            "per-credential signature counters",
            "packed attestation with a locally generated CA chain",
        ],
        "audited_by": ["vuln.uv_bypass", "vuln.attestation", "vuln.device_conformance"],
        "notes": (
            "The PIN/UV protocol is not implemented: a request carrying "
            "pinUvAuthParam raises CTAP2_ERR_PIN_AUTH_INVALID rather than "
            "verifying it.  _uv() therefore has nothing to verify against."
        ),
    },
    "ctaphid.py": {
        "role": "report framing",
        "lines": None,
        "claims": [
            "64-byte reports",
            "init broadcast with nonce echo",
            "channel allocation and expiry",
            "fragmentation and reassembly",
            "HidTransport with loopback, socket, and Linux HID gadget subclasses",
        ],
        "audited_by": [],
        "notes": (
            "INIT uses the broadcast channel and requires a 17-byte reply with a "
            "matching nonce, which is the CTAPHID 11.2 rule.  selftest_hid covers "
            "36 cases.  Not re-audited here: their own suite exercises it directly."
        ),
    },
    "rp_verify.py": {
        "role": "the relying party's verification",
        "lines": None,
        "claims": [
            "registration and assertion verification",
            "packed and none attestation statements",
            "x5c chain validation",
            "FIDO AAGUID extension check",
            "sign counter enforcement",
        ],
        "audited_by": ["vuln.rp_verifier", "vuln.policy_shapes"],
        "notes": (
            "Holds up well against a forged attestation.  Two gaps reported: the "
            "attestation_verified field follows policy rather than the verification, "
            "and no state is retained to catch a verbatim replay."
        ),
    },
    "policy_lab.py": {
        "role": "policy classifier, four enforcement shapes",
        "lines": None,
        "claims": [
            "A_NO_GATE, B_SYNCABILITY, C_ATTEST_PRESENT, D_MDS_TRUSTED",
            "hardkey vs passkey verdict per shape",
            "a forged signature should be rejected by D only",
        ],
        "audited_by": ["vuln.policy_shapes"],
        "notes": (
            "The C shape accepting a forged signature is the project's own stated "
            "finding.  Confirmed by measurement rather than assumed."
        ),
    },
    "analyze_attestation.py": {
        "role": "attestation analyser for RPs",
        "lines": None,
        "claims": [
            "identify rejectable signals and report rp_can_reject per finding",
            "detect the FIDO AAGUID extension",
            "detect an untrusted root",
        ],
        "audited_by": ["vuln.attestation"],
        "notes": (
            "Reports leaf_has_fido_extension=True for a malformed 18-byte value.  "
            "It checks presence, not well-formedness."
        ),
    },
    "ctap2_server / ctaphid_server.py": {
        "role": "device over /dev/hidg0 or TCP",
        "lines": None,
        "claims": [
            "loopback listener by default",
            "non-loopback requires --allow-remote",
            "one client at a time",
        ],
        "audited_by": [],
        "notes": (
            "Loopback-only by default is a sound default for an unauthenticated "
            "listener carrying PIN material."
        ),
    },
    "uhid_ctap.py": {
        "role": "kernel-level HID injection",
        "lines": None,
        "claims": [
            "UHID_CREATE2 on /dev/uhid",
            "FIDO usage page 0xF1D0",
            "enumerates as a USB security key to any browser",
        ],
        "audited_by": [],
        "notes": (
            "Not exercised here: /dev/uhid returns ENODEV on this host, no uhid line "
            "in /proc/misc, no /lib/modules/$(uname -r).  selftest_uhid reports this "
            "as INFO rather than pretending it passed, which is the right behaviour."
        ),
    },
}

CLAIMS_NOT_REACHABLE = {
    "vendor-signed attestation": "needs the vendor CA private key",
    "AAGUID in the FIDO MDS": "needs FIDO Alliance metadata signing",
    "id-fido-gen-ce-aaguid binding": "same root requirement",
}


def render() -> str:
    lines = [
        f"{TARGET} @ {COMMIT}  ({LINES_SRC} lines in src/, "
        f"{LINES_WITH_TESTS} with tests/)",
        "",
    ]
    for name, info in SURFACE.items():
        size = f"{info['lines']} lines" if info.get("lines") else ""
        suffix = f"  {size}" if size else ""
        lines.append(f"{name}  -- {info['role']}{suffix}")
        for claim in info["claims"]:
            lines.append(f"    claims   {claim}")
        if info["audited_by"]:
            lines.append(f"    audited  {', '.join(info['audited_by'])}")
        else:
            lines.append("    audited  (not in this audit)")
        lines.append(f"    note     {info['notes']}")
        lines.append("")
    lines.append("claims that are not reachable")
    for what, why in CLAIMS_NOT_REACHABLE.items():
        lines.append(f"  {what:34s} {why}")
    return "\n".join(lines)


if __name__ == "__main__":
    print(render())
